import { Open_Sans, Roboto, PT_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Sky Creatives",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${roboto.variable} ${ptSans.variable} antialiased font-roboto`}
      >
        <div className="fixed inset-0 -z-10 min-h-screen w-full bg-white bg-[radial-gradient(#e5e7eb_2px,transparent_1px)] [background-size:32px_32px]"></div>
        <nav className="bg-white py-5 border-b-2 border-slate-200 px-[100px] sm:px[30px] md:px-[50px] lg:px-[100px] xl:px-[200px]">
          <div className="container mx-auto flex justify-between items-center text-sm">
            {/* Logo */}
            <Link href="/" className="font-bold hover:text-blue-300">
              Sky Creatives
            </Link>
            {/* Navigation Links */}
            <div className="flex gap-6">
              <Link href="/" className="hover:text-sky-500 transition">
                Home
              </Link>
              <Link href="/about" className="hover:text-sky-500 transition">
                About
              </Link>
              <Link href="/services" className="hover:text-sky-500 transition">
                Services
              </Link>
              <div className="ml-[100px]">
                <Link href="#contact" className="bg-white px-4 py-2 rounded-lg border-2 border-dashed border-slate-200 hover:text-sky-500 hover:border-sky-500 transition">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </nav>
        <div className="container mx-auto px-[100px] sm:px[30px] md:px-[50px] lg:px-[100px] xl:px-[200px]">
        {children}
        </div>
        <footer className="bg-white py-5 border-t-2 border-slate-200 px-[100px] sm:px[30px] md:px-[50px] lg:px-[100px] xl:px-[200px]">
          <div className="container mx-auto py-5">
            <div className="flex justify-between items-center">
              <p className="text-sm text-gray-500">
                &copy; {new Date().getFullYear()} Sky Creatives. All rights
                reserved.
              </p>
              <div className="flex gap-4">
                <Link href="/privacy" className="text-sm text-gray-500 hover:text-sky-500 transition">
                  Privacy Policy
                </Link>
                <Link href="/terms" className="text-sm text-gray-500 hover:text-sky-500 transition">
                  Terms of Service
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
